// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

import { State } from "./../state";
import { getInitializeTemplatingDefaultState } from "./../defaultState.base.generated";
import { InitializeTemplatingReducerActions } from "./../reducerActions/reducerActions.main.generated";

// import { InFormPartialTemplate } from "../../types/Partial";
// import { InFormRootTemplate } from "../../types/RootTemplates";

// import { INITIALIZE_TEMPLATING_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";
// import { INITIALIZE_TEMPLATING_ACTIONS_EXTENDED as actions } from "./../actions/actions.extended";

// Uncomment for some typechecking:
// import { isInitializeTemplatingReducerActionsExtended } from "./../reducerActions/reducerActions.extended";
// import { isInitializeTemplatingReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";

export const initializeTemplatingReducerExtended = (
    state: State = getInitializeTemplatingDefaultState(),
    action: InitializeTemplatingReducerActions
): State => {
    switch (action.type) {
        //         case actions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //            };
        //         case extendedActions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //              };
        default:
            return state;
    }
};

export default initializeTemplatingReducerExtended;
