// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

export enum INITIALIZE_TEMPLATING_ACTIONS_EXTENDED {}
// e.g. ADD_LOADING_HANDLE = "ADD_LOADING_HANDLE",

export default INITIALIZE_TEMPLATING_ACTIONS_EXTENDED;
