// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

export enum SEARCH_MAPPINGS_ACTIONS_EXTENDED {}
// e.g. ADD_LOADING_HANDLE = "ADD_LOADING_HANDLE",

export default SEARCH_MAPPINGS_ACTIONS_EXTENDED;
