#https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Composition Test and Build Node package
# description: 'Greet someone'
inputs:
  packageVersion:
    required: false
    type: string
  artefactName:
    required: false
    type: string
  nodeVersions:
    required: true
    type: string
  folderWithPackage:
    required: true
    type: string
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  # - uses: actions/checkout@v3
  # - name: Using Node.js ${{ matrix.nodeVersion }}
  #   uses: actions/setup-node@v3
  #   with:
  #     node-version: ${{ matrix.nodeVersion }}
  
  - name: perform unittests (${{ inputs.folderWithPackage }})
    shell: bash
    working-directory: ${{ inputs.folderWithPackage }}
    run: |
      npm test
  
  - name: build bundle (${{ inputs.folderWithPackage }})
    shell: bash
    working-directory: ${{ inputs.folderWithPackage }}
    run: |
      npm run build
      rm -rf node_modules

  - name: Publish artefact
    uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.artefactName }}-${{ inputs.packageVersion }}-${{ matrix.nodeVersion }}-run-${{ github.run_id }}
      path: ${{ inputs.folderWithPackage }}
