// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

export enum CREATE_FORM_MODELLS_ACTIONS_EXTENDED {}
// e.g. ADD_LOADING_HANDLE = "ADD_LOADING_HANDLE",

export default CREATE_FORM_MODELLS_ACTIONS_EXTENDED;
