// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

import { State } from "./../state";
import { getSearchMappingsDefaultState } from "./../defaultState.base.generated";
import { SearchMappingsReducerActions } from "./../reducerActions/reducerActions.main.generated";

// import { InFormSourceFileAndFormMapping } from "../../types/InFormSourceFileAndFormMapping";

// import { SEARCH_MAPPINGS_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";
// import { SEARCH_MAPPINGS_ACTIONS_EXTENDED as actions } from "./../actions/actions.extended";

// Uncomment for some typechecking:
// import { isSearchMappingsReducerActionsExtended } from "./../reducerActions/reducerActions.extended";
// import { isSearchMappingsReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";

export const searchMappingsReducerExtended = (
    state: State = getSearchMappingsDefaultState(),
    action: SearchMappingsReducerActions
): State => {
    switch (action.type) {
        //         case actions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //            };
        //         case extendedActions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //              };
        default:
            return state;
    }
};

export default searchMappingsReducerExtended;
