// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

import { State } from "./../state";
import { getSearchGeneralSettingsDefaultState } from "./../defaultState.base.generated";
import { SearchGeneralSettingsReducerActions } from "./../reducerActions/reducerActions.main.generated";

// import { InFormSourceFileAndGeneralSettings } from "../../types/InFormSourceFileAndGeneralSettings";

// import { SEARCH_GENERAL_SETTINGS_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";
// import { SEARCH_GENERAL_SETTINGS_ACTIONS_EXTENDED as actions } from "./../actions/actions.extended";

// Uncomment for some typechecking:
// import { isSearchGeneralSettingsReducerActionsExtended } from "./../reducerActions/reducerActions.extended";
// import { isSearchGeneralSettingsReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";

export const searchGeneralSettingsReducerExtended = (
    state: State = getSearchGeneralSettingsDefaultState(),
    action: SearchGeneralSettingsReducerActions
): State => {
    switch (action.type) {
        //         case actions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //            };
        //         case extendedActions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //              };
        default:
            return state;
    }
};

export default searchGeneralSettingsReducerExtended;
