// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

import { State } from "./../state";
import { getResolveTemplateModelsDefaultState } from "./../defaultState.base.generated";
import { ResolveTemplateModelsReducerActions } from "./../reducerActions/reducerActions.main.generated";

// import { InFormTemplateFormModel } from "../../types/InFormTemplateFormModel";

// import { RESOLVE_TEMPLATE_MODELS_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";
// import { RESOLVE_TEMPLATE_MODELS_ACTIONS_EXTENDED as actions } from "./../actions/actions.extended";

// Uncomment for some typechecking:
// import { isResolveTemplateModelsReducerActionsExtended } from "./../reducerActions/reducerActions.extended";
// import { isResolveTemplateModelsReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";

export const resolveTemplateModelsReducerExtended = (
    state: State = getResolveTemplateModelsDefaultState(),
    action: ResolveTemplateModelsReducerActions
): State => {
    switch (action.type) {
        //         case actions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //            };
        //         case extendedActions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //              };
        default:
            return state;
    }
};

export default resolveTemplateModelsReducerExtended;
