// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

import { State } from "./../state";
import { getCreateFormModellsDefaultState } from "./../defaultState.base.generated";
import { CreateFormModellsReducerActions } from "./../reducerActions/reducerActions.main.generated";

// import { FormModell } from "../../types/FormModell";

// import { CREATE_FORM_MODELLS_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";
// import { CREATE_FORM_MODELLS_ACTIONS_EXTENDED as actions } from "./../actions/actions.extended";

// Uncomment for some typechecking:
// import { isCreateFormModellsReducerActionsExtended } from "./../reducerActions/reducerActions.extended";
// import { isCreateFormModellsReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";

export const createFormModellsReducerExtended = (
    state: State = getCreateFormModellsDefaultState(),
    action: CreateFormModellsReducerActions
): State => {
    switch (action.type) {
        //         case actions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //            };
        //         case extendedActions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //              };
        default:
            return state;
    }
};

export default createFormModellsReducerExtended;
